tailoring/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.Home.as_view(), name='home-page'),
     path('appointments/', views.AppointmentList.as_view(),
          name='appointments'),
     path('appointments/<int:pk>/', views.AppointmentDetail.as_view(),
          name='appointment-detail'),
     path('appointments/new', views.AppointmentCreate.as_view(),
          name='appointment-create'),
     path('appointments/<int:pk>/update', views.AppointmentUpdate.as_view(),
          name='appointment-update'),
     path('appointments/<int:pk>/delete', views.AppointmentDelete.as_view(),
          name='appointment-delete'),
     path('about/', views.About.as_view(), name='about-page'),
     path('services/', views.Services.as_view(), name='services-page'),
]

tailors_thimble/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profile/', views.ProfileUpdateView.as_view(), name='profile'),
    path('', include('tailoring.urls')),
]

tailoring/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import datetime
from .constants import TYPE_CHOICES, TIME_CHOICES


class Appointment(models.Model):
    """
    Defines the Appointment Model
    """
    user = models.ForeignKey(
        User, related_name='appointment', on_delete=models.CASCADE)
    type = models.CharField(
        max_length=15, choices=TYPE_CHOICES, default='')
    date = models.DateField()
    time = models.CharField(
        max_length=8, choices=TIME_CHOICES, default='')
    comments = models.TextField()
    submitted = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """
        Innerclass of Appointment model, changes the behaviour of the fields
        """
        ordering = ['date']

    def __str__(self):
        """
        Returns a string representation
        """
        return f'{self.user}'

    def get_absolute_url(self):
        """
        Returns the full URL to the appointment route as a string
        """
        return reverse('appointments')

tailoring/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import NumberInput
from .models import Appointment
from .constants import TYPE_CHOICES, TIME_CHOICES
from datetime import date


class AppointmentForm(ModelForm):
    """
    Interacts with the Appointment model to let users
    create an appointment
    """
    type = forms.ChoiceField(
                required=True,
                choices=TYPE_CHOICES,
                widget=forms.Select(
                    attrs={'class': 'form-control'}
                )
            )
    date = forms.DateField(
                required=True,
                widget=NumberInput(
                    attrs={'class': 'form-control',
                           'type': 'date'}
                )
            )
    time = forms.ChoiceField(
                required=True,
                choices=TIME_CHOICES,
                widget=forms.Select(
                    attrs={'class': 'form-control'}
                )
            )
    comments = forms.CharField(
                    required=False,
                    max_length=150,
                    widget=forms.Textarea(
                        attrs={'class': 'form-control',
                               'rows': 4}
                    )
                )

    # adapted from https://tinyurl.com/sm6mu2bv
    def clean_date(self):
        """
        Validation for the date
        """
        date = self.cleaned_data['date']
        appointments_on_date = Appointment.objects.filter(date__exact=date)
        # Only dates from tomorrow are accepted
        if date <= date.today():
            raise forms.ValidationError("Please choose a date and time at"
                                        " least 24 hours from now.")
        # Monday and Sunday are not accepted
        if date.weekday() == 0 or date.weekday() == 6:
            raise forms.ValidationError("Sorry, we're only open Tuesday to"
                                        " Saturday.")
        # No more than 5 appointments per day are accepted
        if len(appointments_on_date) > 5:
            raise forms.ValidationError("There are no available appointments"
                                        " left on this day, please try again!")
        return date

    def clean_time(self):
        """
        Checks if date is valid and validates time
        """
        time = self.cleaned_data['time']
        # date needs to be valid first
        if 'date' not in self.cleaned_data:
            raise forms.ValidationError("Please choose a valid date first")
        date = self.cleaned_data['date']
        appointments_on_date = Appointment.objects.filter(date__exact=date)
        times = [a['time'] for a in appointments_on_date.values('time')]
        # time cannot be already in list of times for date selected
        if time in times:
            raise forms.ValidationError("Sorry, there is already an "
                                        "appointment booked for this time.")
        return time

    class Meta:
        model = Appointment
        fields = ['type', 'date', 'time', 'comments']

tailoring/views.py
from django.shortcuts import render
from django.views import View
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin
)
from .models import Appointment
from .forms import AppointmentForm


class Home(View):
    """
    Handles traffic from the Homepage of the Website
    """
    def get(self, request):
        return render(request, 'home.html', {'title': 'Home'})


class About(View):
    """
    Handles the About Page
    """
    def get(self, request):
        return render(request, 'about.html', {'title': 'About'})


class Services(View):
    """
    Handles the Services Page
    """
    def get(self, request):
        return render(request, 'services.html', {'title': 'Services'})


class AppointmentList(LoginRequiredMixin, ListView):
    """
    Defines the logic for the User's Appointments page
    """
    model = Appointment
    context_object_name = 'appointments'

    def get_queryset(self):
        """
        Returns objects that belong to the current user
        """
        return Appointment.objects.filter(user=self.request.user)


class AppointmentDetail(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """
    Defines the logic for each appointment
    """
    model = Appointment

    def test_func(self):
        """
        UserPassesTestMixin runs this method to check if user
        is the user who created the appointment
        """
        appointment = self.get_object()
        if self.request.user == appointment.user:
            return True
        return False


class AppointmentCreate(LoginRequiredMixin, CreateView):
    """
    Defines the logic for the AppointmentForm
    """
    model = Appointment
    form_class = AppointmentForm

    def form_valid(self, form):
        """
        Adds the logged in user before form is submitted
        """
        form.instance.user = self.request.user
        messages.success(self.request,
                         'Your appointment has been created successfully!')
        return super().form_valid(form)

    def form_invalid(self, form):
        """
        Overrides the form_invalid method to add error alerts
        """
        messages.error(self.request,
                       'Sorry an error occurred while creating your '
                       'appointment. Please try again!')
        return super().form_invalid(form)


class AppointmentUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Defines the logic for the Update AppointmentForm
    """
    model = Appointment
    form_class = AppointmentForm
    template_name = 'tailoring/appointment_update.html'

    def form_valid(self, form):
        """
        Adds the logged in user before form is submitted
        """
        form.instance.user = self.request.user
        messages.success(self.request,
                         'Your appointment has been updated successfully!')
        return super().form_valid(form)

    def form_invalid(self, form):
        """
        Overrides the form_invalid method to add error alerts
        """
        messages.error(self.request,
                       'Sorry an error occurred while updating your '
                       'appointment. Please try again!')
        return super().form_invalid(form)

    def test_func(self):
        """
        UserPassesTestMixin runs this method to check if the current
        logged in user matches the user who created the appointment
        """
        appointment = self.get_object()
        if self.request.user == appointment.user:
            return True
        return False


class AppointmentDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Handles the logic for deleting posts
    """
    model = Appointment
    success_url = reverse_lazy('appointments')

    def test_func(self):
        """
        UserPassesTestMixin runs this method to check if the current
        logged in user matches the user who created the appointment
        """
        appointment = self.get_object()
        if self.request.user == appointment.user:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        """
        Dispays an alert on successful deletion
        """
        messages.success(self.request,
                         'Your appointment has been deleted.')
        return super(AppointmentDelete, self).delete(request, *args, **kwargs)

tailoring/templates/tailoring/appointment_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Appointment{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container section-container">
  <div class="card form--app-card rounded shadow col-10 col-md-6 m-auto text-center">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <h2 class="border-bottom mb-4">Delete Appointment</h2>
          <p>Are you sure you want to delete this appointment?</p>
      </fieldset>
        <div class="form-group">
          <button class="btn btn-lg btn-danger mr-4" type="submit">Yes, Delete</button>
          <a class="btn btn-lg btn-outline-primary" role="button" 
            href="{% url 'appointment-detail' object.id %}">Cancel</a>
        </div>    
    </form>
  </div>
</div>
{% endblock %}

tailoring/templates/tailoring/appointment_detail.html
{% extends 'base.html' %}
{% block title %}View Appointment{% endblock %}
{% block content %}

<div class="container section-container">    
    <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        <div class="card app-card mb-2 rounded shadow">
            <div class="card-body">
                <h4 class="card-title text-center">{{ object.get_type_display }}</h4>
                <div class="card-details mb-3">
                    <p><strong>Date: &emsp;&emsp;</strong>{{ object.date }}</p>
                    <p><strong>Time: &emsp;&emsp;</strong>{{ object.get_time_display }}</p>
                    <hr>
                    {% if object.approved %}
                        <div class="text-center">
                            <p>{{ object.user.first_name }}, your appointment has been confirmed! 
                                We look forward to seeing you at:
                            </p>
                            <address>Tailor's Thimble,<br>23, Strada Rjali<br>Valletta, Malta</address>
                        </div>
                    {% else %}
                        <p>We will get in touch with you as soon as possible to confirm or reschedule your appointment.</p>
                    {% endif %}   
                </div>
                <div class="card-footer">
                    <small><i>If you need to reschedule, use the update button below.  We require 24 hours to confirm rescheduling.</i></small>
                    <div class="mt-2 text-center">
                        <a href="{% url 'appointment-update' object.id %}" 
                            role="button" class="btn btn-lg btn-primary mr-4">Update</a>
                        <a href="{% url 'appointment-delete' object.id %}" 
                            role="button" class="btn btn-lg btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-6 mt-3 offset-md-2 offset-lg-3">
                <div class="row justify-content-center mb-4">
                    <a href="{% url 'appointments' %}" role="button"
                        class="btn btn-lg btn-outline-primary shadow">Back to Appointments</a>
                </div>
            </div>
        </div>
    </div>        
</div>
{% endblock content %}

tailoring/templates/tailoring/appointment_form.html
{% extends 'base.html' %}
{% block title %}Create Appointment{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.profile.event %}
  <div class="container section-container">
    <div class="card form--app-card rounded shadow col-10 col-md-8 col-lg-6 m-auto">
      <div class="text-center col-lg-10 m-auto">
        <h2>Schedule an Appointment</h2>
        <p>Thank you for your interest.<br>Please fill in the form below, 
          specifying in the comment box any other requirements.
          We may get in touch to change your appointment if your deadline 
          is sooner than our minimum window.
        </p>
        <p class="border-bottom mb-3">Use our guidelines on the 
          <a class="link-txt" href="{% url 'about-page' %}#process" target="_blank" 
          aria-label="The Bespoke Process (opens in a new tab)">Process </a>to select the appropriate
          type of appointment for your booking.
        </p>
      </div>
      <div class="row">
        <div class="col-md-8 col-lg-6 mt-2 offset-md-2 offset-lg-3">
          <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              {{ form|crispy }}
            </fieldset>
              <div class="form-group">
                <button class="btn btn-lg btn-primary mb-2" type="submit">Submit</button>
              </div>    
          </form>
        </div>
      </div>
    </div>
    <div class="text-center mt-3 mb-4">
      <a class="btn btn-lg btn-outline-primary shadow" role="button" 
        href="{% url 'appointments' %}">Back to Appointments</a>
    </div>
  </div>
{% else %}
<div class="container mt-4 mb-4">
  <div class="row">
      <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-3">
          <div class="card-body no-profile">
              <div class="border-bottom mb-4">
                <h2>Oops sorry {{ user.username }}</h2>
                <p>Before you make an appointment, we need to know a few things about 
                  the outfit you need.
                </p>    
                <p>We would appreciate if you could please head 
                  back to your <a class="link-txt" href="{% url 'profile'  %}">Profile Page</a>  
                  and fill in your requirements.
                </p>
              </div>    
          </div>
      </div>
  </div>
</div>
{% endif %}
{% endblock %}

tailoring/templates/tailoring/appointment_list.html
{% extends 'base.html' %}
{% block title %}Appointments{% endblock %}
{% block content %}

<div class="container">    
    <div class="row">
        <div class="col-md-10 offset-md-1 mt-4 mb-4 d-md-flex justify-content-between align-items-center text-center text-md-left">
            <h1>{{ user.username }}'s Appointments</h1>
            <a href="{% url 'appointment-create' %}" 
                role="button" class="btn btn-primary btn-lg">Add Appointment
            </a>
        </div>
        {% if appointments %}
        <div class="container">
            <div class="row">
                <div class="col-md-12 d-md-flex flex-wrap justify-content-around">  
                    {% for appointment in appointments %}
                        <div class="card app-card mb-4 mr-md-4 rounded shadow" style="min-width: 28rem;">
                            <div class="card-body">
                                <h2 class="card-title text-center">{{ appointment.get_type_display }}</h2>
                                <div class="card-details mb-3">
                                    <p><strong>Date: &emsp;&emsp;</strong>{{ appointment.date }}</p>
                                    <p><strong>Time: &emsp;&emsp;</strong>{{ appointment.get_time_display }}</p><hr>
                                    <p><strong>Approved: &nbsp;</strong>{{ appointment.approved|yesno:"Yes,No" }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'appointment-detail' appointment.id %}" 
                                    role="button" class="btn btn-outline-primary">View Appointment</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% else %}    
        <div class="container section-container">
            <div class="card rounded shadow col-10 col-md-8 col-lg-6 m-auto">
                <div class="card-body">
                    <div class="text-center p-4">
                        <h2 class="border-bottom">Welcome to your Appointments page {{ user.first_name }} {{ user.last_name }}!</h2>
                        <p>You have no appointments scheduled yet.</p>
                        <p>Please use the "Add Appointment" button above to schedule 
                            your free consultation now.
                        </p>
                    </div>    
                </div>
            </div>
        </div>
        {% endif %}
    </div>        
</div>
{% endblock content %}

tailoring/templates/tailoring/appointment_update.html
{% extends 'base.html' %}
{% block title %}Update Appointment{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container section-container">
  <div class="card form--app-card rounded shadow col-10 col-md-8 col-lg-6 m-auto">
    <div class="text-center col-lg-10 m-auto">
      <h2>Edit Appointment</h2>
    </div>
    <div class="row">
      <div class="col-md-8 col-lg-6 mt-2 offset-md-2 offset-lg-3">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
            {{ form|crispy }}
          </fieldset>
          <div class="form-group">
            <button class="btn btn-lg btn-primary" type="submit">Update</button>
          </div>    
        </form>
      </div>
    </div>
  </div>
  <div class="text-center mt-3 mb-4">
    <a class="btn btn-lg btn-outline-primary shadow" role="button" 
      href="{% url 'appointments' %}">Back to Appointments</a>
  </div>
</div>
{% endblock %}